using System.Net.Http.Headers;
using System.Text.Json;
using FeatherPod.Shared.Models;
using FeatherPod.Settings.Episode;
using Microsoft.Extensions.Configuration;
using Spectre.Console;

namespace FeatherPod.Infrastructure;

internal static class EpisodeHelpers
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    internal static async Task ListEpisodesAsync(HttpClient httpClient, FeedConfig feed)
    {
        try
        {
            var response = await httpClient.GetAsync($"/api/feeds/{feed.Id}/episodes");
            response.EnsureSuccessStatusCode();

            var json = await response.Content.ReadAsStringAsync();
            var episodes = JsonSerializer.Deserialize<List<Episode>>(json, JsonOptions) ?? [];

            AnsiConsole.MarkupLine($"Feed: [cyan]{Markup.Escape(feed.Title)}[/]");
            AnsiConsole.WriteLine();

            if (episodes.Count == 0)
            {
                AnsiConsole.MarkupLine("[yellow]No episodes found.[/]");
                return;
            }

            var table = new Table();
            table.Border(TableBorder.Rounded);
            table.AddColumn("#");
            table.AddColumn("Published");
            table.AddColumn("Title");
            table.AddColumn("URL");
            table.AddColumn("Size");
            table.AddColumn("Duration");

            for (var i = 0; i < episodes.Count; i++)
            {
                var episode = episodes[i];
                var formattedDate = episode.PublishedDate.ToString("yyyy-MM-dd HH:mm");
                var formattedSize = FormatFileSize(episode.FileSize);
                var formattedDuration = FormatDuration(episode.Duration);

                table.AddRow(
                    $"[grey]{i + 1}[/]",
                    $"[grey]{formattedDate}[/]",
                    Markup.Escape(episode.Title),
                    $"[cyan]{Markup.Escape(episode.Url ?? string.Empty)}[/]",
                    formattedSize,
                    formattedDuration
                );
            }

            AnsiConsole.Write(table);
            AnsiConsole.WriteLine();
            AnsiConsole.MarkupLine($"[grey]Total: {episodes.Count} episodes[/]");
        }
        catch (HttpRequestException ex)
        {
            AnsiConsole.MarkupLine($"[red]Error fetching episodes:[/] {ex.Message}");
        }
    }

    private static bool ConfirmDelete(Episode episode)
    {
        return new MenuBuilder<bool?>()
            .WithTitle($"[red]Delete[/] {Markup.Escape(episode.Title)}?")
            .WithHint("(arrow keys or Y/N, Esc to cancel)")
            .AddOption("Y", "Yes", true)
            .AddOption("N", "No", false)
            .AllowCancel(true, false)
            .Show() ?? false;
    }

    private static int SelectEpisode(List<Episode> episodes)
    {
        var menu = new MenuBuilder<int?>()
            .WithTitle("Select episode to [red]delete[/]:")
            .AllowCancel();

        for (var i = 0; i < episodes.Count; i++)
        {
            var episode = episodes[i];
            menu.AddOption(
                null,
                "", // Label will be generated by formatter
                i,
                _ => $"[grey]({episode.PublishedDate:yyyy-MM-dd})[/] {Markup.Escape(episode.Title)}"
            );
        }

        return menu.Show() ?? -1;
    }

    /// <summary>
    /// Interactive episode deletion. Returns true if deleted, false if error, null if cancelled.
    /// </summary>
    internal static async Task<bool?> DeleteEpisodeInteractiveAsync(HttpClient httpClient, FeedConfig feed)
    {
        try
        {
            var response = await httpClient.GetAsync($"/api/feeds/{feed.Id}/episodes");
            response.EnsureSuccessStatusCode();

            var json = await response.Content.ReadAsStringAsync();
            var episodes = JsonSerializer.Deserialize<List<Episode>>(json, JsonOptions) ?? [];

            if (episodes.Count == 0)
            {
                AnsiConsole.MarkupLine("[yellow]No episodes to delete.[/]");
                return false;
            }

            // Use custom selector with Escape support
            var selectedIndex = SelectEpisode(episodes);

            if (selectedIndex == -1)
            {
                return null; // Cancelled
            }

            var episodeToDelete = episodes[selectedIndex];

            // Custom confirmation with Escape support
            var confirmed = ConfirmDelete(episodeToDelete);
            if (!confirmed)
            {
                return null; // Cancelled
            }

            var deleteResponse = await httpClient.DeleteAsync($"/api/feeds/{feed.Id}/episodes/{episodeToDelete.Id}");

            if (deleteResponse.IsSuccessStatusCode)
            {
                AnsiConsole.MarkupLine($"[green]✓[/] Deleted: {Markup.Escape(episodeToDelete.Title)}");
                return true;
            }
            else if (deleteResponse.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                AnsiConsole.MarkupLine("[yellow]Episode not found (may have already been deleted).[/]");
                return false;
            }
            else if (deleteResponse.StatusCode == System.Net.HttpStatusCode.Unauthorized)
            {
                AnsiConsole.MarkupLine("[red]Unauthorized:[/] Check your API key configuration.");
                return false;
            }
            else
            {
                var errorContent = await deleteResponse.Content.ReadAsStringAsync();
                AnsiConsole.MarkupLine($"[red]Failed to delete episode:[/] {deleteResponse.StatusCode}");
                if (!string.IsNullOrEmpty(errorContent))
                {
                    AnsiConsole.MarkupLine($"[red]Error:[/] {errorContent}");
                }
                return false;
            }
        }
        catch (HttpRequestException ex)
        {
            AnsiConsole.MarkupLine($"[red]Error deleting episode:[/] {ex.Message}");
            return false;
        }
    }

    internal static List<string> ExpandFilePatterns(string input)
    {
        var result = new List<string>();

        // Split by comma for comma-separated lists
        var patterns = input.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        foreach (var pattern in patterns)
        {
            // Check if pattern contains wildcards
            if (pattern.Contains('*') || pattern.Contains('?'))
            {
                // Get directory and search pattern
                var directory = Path.GetDirectoryName(pattern);
                var searchPattern = Path.GetFileName(pattern);

                // If no directory specified, use current directory
                if (string.IsNullOrEmpty(directory))
                    directory = Directory.GetCurrentDirectory();

                if (Directory.Exists(directory))
                {
                    var matchingFiles = Directory.GetFiles(directory, searchPattern);
                    result.AddRange(matchingFiles);
                }
            }
            else
            {
                // Regular file path
                if (File.Exists(pattern))
                {
                    result.Add(pattern);
                }
            }
        }

        return result;
    }

    internal static async Task<bool> UploadEpisodeAsync(HttpClient httpClient, IConfiguration configuration, FeedConfig feed, string filePath, PushSettings settings)
    {
        var fileName = Path.GetFileName(filePath);
        var success = false;
        string? normalizedTempFile = null;

        // Extract creation time from ORIGINAL file if requested (before normalization)
        string? extractedPublishedDate = null;
        if (settings.ExtractDateFromFile == true)
        {
            var creationTime = FFmpegService.ExtractCreationTime(filePath);
            if (creationTime.HasValue)
            {
                extractedPublishedDate = creationTime.Value.ToString("o"); // ISO 8601 format
            }
        }

        try
        {
            // Load audio normalization configuration
            var normalizationConfig = new AudioNormalizationConfig();
            configuration.GetSection("AudioNormalization").Bind(normalizationConfig);

            // Check if normalization is enabled
            var fileToUpload = filePath;
            if (normalizationConfig.Enabled)
            {
                // Check if FFmpeg is available
                if (!FFmpegService.IsFFmpegAvailable())
                {
                    AnsiConsole.WriteLine();
                    AnsiConsole.MarkupLine("[yellow]Warning:[/] FFmpeg is not installed or not found in PATH.");
                    AnsiConsole.MarkupLine("  Audio normalization requires FFmpeg to be installed.");
                    AnsiConsole.MarkupLine("  Download from: [link]https://ffmpeg.org/download.html[/]");
                    AnsiConsole.WriteLine();

                    var continueWithoutNormalization = new MenuBuilder<bool?>()
                        .WithTitle("Continue upload without normalization?")
                        .WithHint("(arrow keys or Y/N, Esc to cancel)")
                        .AddOption("Y", "Yes - Upload original file", true)
                        .AddOption("N", "No - Cancel upload", false)
                        .AllowCancel(true, false)
                        .Show();

                    if (continueWithoutNormalization != true)
                    {
                        AnsiConsole.MarkupLine("[grey]Upload cancelled.[/]");
                        return false;
                    }
                    AnsiConsole.WriteLine();
                }
                else
                {
                    // Normalize audio
                    AnsiConsole.MarkupLine($"Normalizing [cyan]{fileName}[/] to -16 LUFS...");
                    normalizedTempFile = await FFmpegService.NormalizeAudioAsync(filePath, normalizationConfig);

                    if (normalizedTempFile == null)
                    {
                        AnsiConsole.WriteLine();
                        AnsiConsole.MarkupLine("[yellow]Warning:[/] Audio normalization failed.");

                        var continueWithOriginal = new MenuBuilder<bool?>()
                            .WithTitle("Continue upload with original (unnormalized) file?")
                            .WithHint("(arrow keys or Y/N, Esc to cancel)")
                            .AddOption("Y", "Yes - Upload original file", true)
                            .AddOption("N", "No - Cancel upload", false)
                            .AllowCancel(true, false)
                            .Show();

                        if (continueWithOriginal != true)
                        {
                            AnsiConsole.MarkupLine("[grey]Upload cancelled.[/]");
                            return false;
                        }
                        AnsiConsole.WriteLine();
                    }
                    else
                    {
                        fileToUpload = normalizedTempFile;
                        AnsiConsole.MarkupLine("[green]✓[/] Audio normalized successfully");
                        AnsiConsole.WriteLine();
                    }
                }
            }

            await AnsiConsole.Status()
                .StartAsync($"Uploading [cyan]{fileName}[/]...", async _ =>
                {
                    try
                    {
                        // Create multipart form data
                        using var content = new MultipartFormDataContent();

                        // Add file (use normalized file if available, otherwise original)
                        var fileBytes = await File.ReadAllBytesAsync(fileToUpload);
                        var fileContent = new ByteArrayContent(fileBytes);
                        fileContent.Headers.ContentType = new MediaTypeHeaderValue("audio/mpeg");
                        content.Add(fileContent, "file", fileName);

                        // Add optional title
                        if (!string.IsNullOrEmpty(settings.Title))
                        {
                            content.Add(new StringContent(settings.Title), "title");
                        }

                        // Add optional description
                        if (!string.IsNullOrEmpty(settings.Description))
                        {
                            content.Add(new StringContent(settings.Description), "description");
                        }

                        // Add optional summary
                        if (!string.IsNullOrEmpty(settings.Summary))
                        {
                            content.Add(new StringContent(settings.Summary), "summary");
                        }

                        // Add published date options
                        if (!string.IsNullOrEmpty(settings.PublishedDate))
                        {
                            content.Add(new StringContent(settings.PublishedDate), "publishedDate");
                        }
                        else if (!string.IsNullOrEmpty(extractedPublishedDate))
                        {
                            // Use extracted date from original file (before normalization)
                            content.Add(new StringContent(extractedPublishedDate), "publishedDate");
                        }
                        // Note: UseCurrentDate is the default behavior, no need to send anything

                        // Upload
                        var response = await httpClient.PostAsync($"/api/feeds/{feed.Id}/episodes", content);

                        if (response.IsSuccessStatusCode)
                        {
                            success = true;
                            var responseContent = await response.Content.ReadAsStringAsync();
                            var episode = JsonSerializer.Deserialize<Episode>(responseContent, JsonOptions);

                            AnsiConsole.MarkupLine($"[green]✓[/] Uploaded: [cyan]{fileName}[/]");
                            AnsiConsole.WriteLine();

                            if (episode != null)
                            {
                                AnsiConsole.MarkupLine($"  ID: [grey]{episode.Id}[/]");
                                AnsiConsole.MarkupLine($"  Title: {Markup.Escape(episode.Title)}");
                                AnsiConsole.MarkupLine($"  Published: [grey]{episode.PublishedDate:yyyy-MM-dd HH:mm:ss}[/]");
                                AnsiConsole.MarkupLine($"  Duration: [grey]{FormatDuration(episode.Duration)}[/]");
                                AnsiConsole.MarkupLine($"  Size: [grey]{FormatFileSize(episode.FileSize)}[/]");
                            }
                        }
                        else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                        {
                            AnsiConsole.MarkupLine($"[red]✗[/] Unauthorized: Check your API key configuration");
                        }
                        else
                        {
                            var errorContent = await response.Content.ReadAsStringAsync();
                            AnsiConsole.MarkupLine($"[red]✗[/] Failed to upload [cyan]{fileName}[/]: {response.StatusCode}");
                            if (!string.IsNullOrEmpty(errorContent))
                            {
                                AnsiConsole.MarkupLine($"  [red]Error:[/] {errorContent}");
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        AnsiConsole.MarkupLine($"[red]✗[/] Error uploading [cyan]{fileName}[/]: {ex.Message}");
                    }
                });

            return success;
        }
        finally
        {
            // Clean up normalized temp file
            if (normalizedTempFile != null && File.Exists(normalizedTempFile))
            {
                try
                {
                    File.Delete(normalizedTempFile);
                }
                catch
                {
                    // Ignore cleanup errors
                }
            }
        }
    }

    internal static string FormatFileSize(long bytes)
    {
        string[] sizes = ["B", "KB", "MB", "GB"];
        double len = bytes;
        var order = 0;

        while (len >= 1024 && order < sizes.Length - 1)
        {
            order++;
            len /= 1024;
        }

        return $"{len:0.##} {sizes[order]}";
    }

    internal static string FormatDuration(TimeSpan duration)
    {
        return duration.TotalHours >= 1
            ? $"{(int)duration.TotalHours}:{duration.Minutes:D2}:{duration.Seconds:D2}"
            : $"{duration.Minutes}:{duration.Seconds:D2}";
    }

    internal static async Task<List<Episode>?> GetEpisodesAsync(HttpClient httpClient, string feedId)
    {
        try
        {
            var response = await httpClient.GetAsync($"/api/feeds/{feedId}/episodes");

            if (!response.IsSuccessStatusCode)
            {
                AnsiConsole.MarkupLine($"[red]Error:[/] Failed to fetch episodes from feed '{feedId}'");
                return null;
            }

            var json = await response.Content.ReadAsStringAsync();
            var episodes = JsonSerializer.Deserialize<List<Episode>>(json, JsonOptions);
            return episodes;
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine($"[red]Error fetching episodes:[/] {ex.Message}");
            return null;
        }
    }

    internal static async Task<bool> MoveEpisodeAsync(HttpClient httpClient, string fromFeed, string episodeId, string toFeed)
    {
        try
        {
            var requestBody = new { targetFeedId = toFeed };
            var json = JsonSerializer.Serialize(requestBody);
            var content = new StringContent(json, System.Text.Encoding.UTF8, "application/json");

            var response = await httpClient.PostAsync($"/api/feeds/{fromFeed}/episodes/{episodeId}/move", content);

            if (!response.IsSuccessStatusCode)
            {
                var errorJson = await response.Content.ReadAsStringAsync();
                var errorObj = JsonSerializer.Deserialize<JsonElement>(errorJson);
                var errorMsg = errorObj.TryGetProperty("error", out var err) ? err.GetString() : "Unknown error";
                AnsiConsole.MarkupLine($"[red]Error:[/] {errorMsg}");
                return false;
            }

            return true;
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine($"[red]Error moving episode:[/] {ex.Message}");
            return false;
        }
    }

    internal static async Task<bool> CopyEpisodeAsync(HttpClient httpClient, string fromFeed, string episodeId, string toFeed)
    {
        try
        {
            var requestBody = new { targetFeedId = toFeed };
            var json = JsonSerializer.Serialize(requestBody);
            var content = new StringContent(json, System.Text.Encoding.UTF8, "application/json");

            var response = await httpClient.PostAsync($"/api/feeds/{fromFeed}/episodes/{episodeId}/copy", content);

            if (!response.IsSuccessStatusCode)
            {
                var errorJson = await response.Content.ReadAsStringAsync();
                var errorObj = JsonSerializer.Deserialize<JsonElement>(errorJson);
                var errorMsg = errorObj.TryGetProperty("error", out var err) ? err.GetString() : "Unknown error";
                AnsiConsole.MarkupLine($"[red]Error:[/] {errorMsg}");
                return false;
            }

            return true;
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine($"[red]Error copying episode:[/] {ex.Message}");
            return false;
        }
    }

    internal static List<Episode> SelectEpisodesMulti(List<Episode> episodes)
    {
        if (episodes.Count == 0)
        {
            return [];
        }

        var prompt = new MultiSelectionPrompt<Episode>()
            .Title("Select episodes:")
            .PageSize(10)
            .Required()
            .MoreChoicesText("[grey](Move up/down for more)[/]")
            .InstructionsText("[grey]([blue]Space[/] to toggle, [green]Enter[/] to confirm)[/]")
            .UseConverter(ep => $"[grey]{ep.PublishedDate:yyyy-MM-dd}[/] {Markup.Escape(ep.Title)}")
            .AddChoices(episodes);

        return AnsiConsole.Prompt(prompt);
    }

    internal static List<Episode> MatchEpisodesByPattern(List<Episode> episodes, string pattern)
    {
        // Try exact ID match first
        var exactMatch = episodes.FirstOrDefault(e => e.Id == pattern);
        if (exactMatch != null) return [exactMatch];

        // Wildcard match on filename or title (case-insensitive)
        if (pattern == "*") return episodes;

        var lower = pattern.ToLower();

        // Contains pattern: *text*
        if (pattern.StartsWith("*") && pattern.EndsWith("*"))
        {
            var contains = lower.Trim('*');
            return episodes.Where(e =>
                e.FileName.ToLower().Contains(contains) ||
                e.Title.ToLower().Contains(contains)).ToList();
        }

        // Prefix pattern: text*
        if (pattern.EndsWith("*"))
        {
            var prefix = lower[..^1];
            return episodes.Where(e =>
                e.FileName.ToLower().StartsWith(prefix) ||
                e.Title.ToLower().StartsWith(prefix)).ToList();
        }

        // Suffix pattern: *text
        if (pattern.StartsWith("*"))
        {
            var suffix = lower[1..];
            return episodes.Where(e =>
                e.FileName.ToLower().EndsWith(suffix) ||
                e.Title.ToLower().EndsWith(suffix)).ToList();
        }

        // Literal match (no wildcards) - match filename or title
        return episodes.Where(e =>
            e.FileName.Equals(pattern, StringComparison.OrdinalIgnoreCase) ||
            e.Title.Equals(pattern, StringComparison.OrdinalIgnoreCase)).ToList();
    }
}
